### ISSUE TITLE
Corrupted intensities from an eFTIR spc file

### ISSUE THREAD

**Issue by jveitchmichaelis** [rohanisaac/spc#10]
Hi, 

I've got an .spc file generated with eFTIR that I'd like to open. It seems that the module loads the wavenumbers correctly, but mangles the intensities.

I've attached the files here, there's the original spc file, the correct output from eFTIR (converted as a CSV) and the incorrect output from the python module. The correct output is (I believe) in counts, up to few tens of thousands while the module output are floats between -0.3 and 0.3.

Any idea what's going wrong here?

[spc_to_txt_test.zip](https://github.com/rohanisaac/spc/files/468406/spc_to_txt_test.zip)

Many thanks!

**Comment by jveitchmichaelis** [comment]
So having had a look in a hex editor it seems that it's an encoding issue. I had a look in a hex editor, the first non-zero byte group is 30 2A E1 46 which corresponds to the correct 28821.093750.

It looks like the file isn't defining any subheader info and `subexp` is set to zero. This in turn means the file is interpreted as ints rather than floats. I fixed it by adding:

    if self.subexp == 0:
        self.subexp = 128

Which is enough for a quick fix, but whether this is appropriate action (in general) if the header is missing I don't know.

**Comment by rohanisaac** [comment]
I recall seeing something like this before, let me take a look and see if I can fix it generally.

**Comment by rohanisaac** [comment]
I rewrote the algorithm for choosing the exponent and it seems to work on all test cases. Instead of trying to guess which of `fexp` or `subexp` is a better exponent, if `tmulti` is not set I use `fexp`, otherwise I use `subexp`. Let me know if you run into other problems.

**Comment by jveitchmichaelis** [comment]
Very late, but yes this worked! Thanks :)
