### ISSUE TITLE
Where the format strings were obtained?

### ISSUE THREAD

**Issue by colinzhao** [rohanisaac/spc#12]
This is not a issue. Just a questions.

Is there any documentation about the spc file? Where did you obtain the file format specifications, e.g. file head format string?

The reference link seems not working if it was from that reference.

**Comment by rohanisaac** [comment]
I'm not sure why the link is now broken, but the internet archive seem to have a working copy: http://web.archive.org/web/20150131073636/http://ftirsearch.com/features/converters/spcfileformat.HTM

**Comment by colinzhao** [comment]
Thanks.
