### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by kitchenknif** [rohanisaac/spc#5]
Anything keeping you from supporting Python3?
The project has been ported to Python3 at least twice, as far as I remember it wasn't too hard, 2to3 took care of most of it, only a couple of things had to bee done by hand.
So I think it should be easy to have both Python2 and Python3 support at the same time...

**Comment by rohanisaac** [comment]
Yeah, I agree, I don't think it would be hard to support both, I'll get that going pretty soon

**Comment by kitchenknif** [comment]
Great, works with Python 3.5 as of a46a587f019b6b511f9e0406187fad6bb3bbdbe9 for my purposes.
Going to kill my fork soon.
Thanks!

**Comment by rohanisaac** [comment]
Great to hear, let me know if you run into any bugs, I'm still a little unfamiliar with Python3.
